// FUNCAO DE LOGIN (USER,SENHA)
// FAZ O LOGIN DO USUARIO E REDIRECIONA PARA A PAGINA DE HOME

//FAZER LOGOUT
//FUNCYYYYYYYYYYYYYYYY

//DAJSKDJAKSDLJ

//FAZER O LOGIN DO USUARIO E REDIRECIONA PARA A PAGINA DE HOME