// FUNCAO DE LOGIN (USER,SENHA)
// FAZ O LOGIN DO USUARIO E REDIRECIONA PARA A PAGINA DE HOME

//FAZER LOGOUT
//DJDKASJDKLAJSDLKJSA
//381290381209

//DAJSKDJAKSDLJ

//FAZER O LOGIN DO USUARIO E REDIRECIONA PARA A PAGINA DE HOME

//nova funcionalidade